name: tz_app_2_salary_leftovers_collector
description: "Salary Leftovers Collector"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  camera: ^0.11.0+2
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  in_app_review: ^2.0.9
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  intl: ^0.20.2
  uuid: ^4.5.3
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.3
  flutter_local_notifications: ^22.0.0
  timezone: ^0.11.0
  shimmer: ^3.0.0
  community_charts_flutter: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
